app/models.py
from . import db


class Manufacturer(db.Model):
    __tablename__ = 'manufacturers'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64), unique=True)
    automobiles = db.relationship('Automobile', backref='manufacturer',
                                  lazy='dynamic', order_by='Automobile.name')

    def __repr__(self):
        return '<Manufacturer %r>' % self.name


class Automobile(db.Model):
    __tablename__ = 'automobiles'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64))
    manufacturer_id = db.Column(db.Integer, db.ForeignKey('manufacturers.id'),
                                nullable=False)

    def __repr__(self):
        return '<Automobile %r>' % self.name

app/main/forms.py
from flask.ext.wtf import Form
from wtforms import StringField, SubmitField
from wtforms.validators import Required


class NameForm(Form):
    name = StringField('What is your name?', validators=[Required()])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from flask.ext.bootstrap import Bootstrap
from flask.ext.mail import Mail
from flask.ext.moment import Moment
from flask.ext.sqlalchemy import SQLAlchemy
from config import config

bootstrap = Bootstrap()
mail = Mail()
moment = Moment()
db = SQLAlchemy()


def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    bootstrap.init_app(app)
    mail.init_app(app)
    moment.init_app(app)
    db.init_app(app)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, errors

app/main/views.py
from flask import render_template, session, redirect, url_for, current_app
from ..models import Manufacturer
from . import main


@main.route('/', methods=['GET', 'POST'])
def index():
    manufacturers = Manufacturer.query.order_by(Manufacturer.name).all()
    return render_template('index.html', manufacturers=manufacturers)

app/templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}Auto Store{% endblock %}

{% block head %}
{{ super() }}
<link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
<link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
{% endblock %}

{% block navbar %}
<div class="navbar navbar-inverse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url_for('main.index') }}">Auto Store</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{{ url_for('main.index') }}">Home</a></li>
            </ul>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
    {% for message in get_flashed_messages() %}
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
    </div>
    {% endfor %}

    {% block page_content %}{% endblock %}
</div>
{% endblock %}

{% block scripts %}
{{ super() }}
{{ moment.include_moment() }}
{% endblock %}

app/templates/index.html
{% extends "base.html" %}

{% block title %}Auto Store{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>Auto Store</h1>
</div>

{% for man in manufacturers %}
<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">{{ man.name }}</h3>
    </div>
    <div class="panel-body">
        <ul class="list-group">
        {% for auto in man.automobiles %}
            <li class="list-group-item">{{ auto.name }}</li>
        {% endfor %}
        </ul>
    </div>
</div>
{% endfor %}

{% endblock %}